name: Prebuilt repo + Snyk Security Scanning (OS)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js for installing Snyk 
      uses: actions/setup-node@v2
      with:
        node-version: 18.4

    # Install & prepare Snyk
    - run: npm install --location=global snyk
      
    - run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Snyk OS Scanning
      run: snyk test --file=app/build.gradle
      continue-on-error: true
      
    - name: Snyk OS monitoring
      run: snyk monitor --file=app/build.gradle --org=dfe66b48-2bf2-4396-b77a-dfdb980e2cf8
      continue-on-error: true
      
